### ISSUE TITLE
Upgrade from Eclipse Aether to Apache Maven Artifact Resolver

### ISSUE THREAD

**Issue by ghost** [snyk/snyk-maven-plugin#23]
This project utilises Eclipse Aether. However Aether was terminated by the Eclipse Foundation in 2016, with the project landing with the Apache Maven project and now known as 'Artifact Resolver.'  

I was looking through to see if I could extend the plugin to ignore 'test' dependencies but am hesitant to dive deeply into Aether, which I'm unfamiliar with and whose repos and docs are no longer available from Eclipse.

Termination note: https://projects.eclipse.org/projects/technology.aether/reviews/termination-review

Apache Maven Artifact Resolver: https://maven.apache.org/resolver/index.html

**Comment by JackuB** [comment]
The [Maven Plugin v2](https://github.com/snyk/snyk-maven-plugin/releases/tag/v2.0.0) is not using these dependencies anymore as it's based on the Snyk CLI
