### ISSUE TITLE
Proxy settings are ignored

### ISSUE THREAD

**Issue by wingzord** [snyk/snyk-maven-plugin#24]
### Expected behaviour
Proxy details are provided in the settings.xml
Plugin should use this details to make connections to the outisde

### Actual behaviour
Proxy is provided in settings.xml
DNS Resolve failed
Proxy settings ignored

### Steps to reproduce
Add proxy details in settings.xml (in .m2 folder)
try to run mvn snyk;test
(Failure will happen when trying to contact snyk.io)

**Comment by sfat** [comment]
@lili2311 I can take this, if this still is needed

**Comment by 123Haynes** [comment]
I just stumbled upon this as well.  
The proxy settings are being ignored, which unfortunately means that I can't use the plugin in our environment and have to stick to using the cli. :crying_cat_face: 

@sfat Proxy support would be greatly appreciated. :smiley:

**Comment by sfat** [comment]
@123Haynes ,
I've made a branch for the fix (https://github.com/sfat/snyk-maven-plugin/tree/proxy-support)
It's hard for me to test this as I can only find proxy servers which are free.
Can you pull the branch and install it in your local maven cache and see if it's working with your proxy server?

**Comment by 123Haynes** [comment]
@sfat Works perfectly :) Thank you.

**Comment by sfat** [comment]
@123Haynes, nice!
I'll create a PR for the fix.

**Comment by sfat** [comment]
@yuliabaron, I think this can be closed.
