### ISSUE TITLE
Internal repositories considered?

### ISSUE THREAD

**Issue by madchap** [snyk/snyk-maven-plugin#28]
- `mvn --version`: 3.6.0

### Expected behaviour
Artifacts from private repositories get pulled and the snyk plugin to find all dependencies.

The snyk CLI has no issue, however. I would expect the two to find the same dependencies.

### Actual behaviour
`mvn snyk:test` or `mvn snyk:monitor` find very little dependencies, totally different than CLI snyk. In current state, it is useless.

### Steps to reproduce
* Configure maven to link against private repos, where private artifacts can be found.
* `mvn snyk:test`
* See that many expected dependencies do not show up.

### Other
* It may seem that `ProjectTraversal.java`, l. 66 could be a pointer? 
* Investigating also with @Wadeck around that line, and also checking with the `JavaScopes` (i.e. COMPILE Vs PROVIDED) as some of our stuff are marked with scope `<provided>`.

**Comment by madchap** [comment]
@lirantal (related to Slack thread). Cheers!

**Comment by lili2311** [comment]
@madchap We have released support for this now, please try it out?
