### ISSUE TITLE
mvn snyk:monitor shows internal server error since 21 june 2019

### ISSUE THREAD

**Issue by marconew10** [snyk/snyk-maven-plugin#30]
- `mvn --version`:
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T19:39:06Z)
Maven home: /root/.maven/apache-maven-3.5.0
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.4.0-1052-aws", arch: "amd64", family: "unix"

### Expected behaviour
[INFO] Captured a snapshot of this project's dependencies.
[INFO] Explore this snapshot at https://snyk.io/org/new10/monitor/aaa99e28-3429-4c65-a4ac-ec1c93aff2aa
[INFO] 
[INFO] Notifications about newly disclosed vulnerabilities related to these dependencies will be emailed to you.
[INFO] 
[INFO]

### Actual behaviour
[ERROR] Bad response from Snyk: HTTP/1.1 500 Internal Server Error

### Steps to reproduce
Run mvn snyk:monitor on a project

Best regards,
Marco

**Comment by adrukh** [comment]
@marconew10 thanks for reporting this, can you please email support@snyk.io with the details? We'll take it there.

**Comment by lili2311** [comment]
Is this still an issue for you @marconew10?

**Comment by marconew10** [comment]
Hello Lili,


No it isn't anymore, the upgrade to the latest version of the plugin fixed it.

Btw: I already responded that on the related created Snyk internal issue weeks ago AFAICR...  :)


Best regards,

Marco
New10

________________________________

**Comment by sfat** [comment]
@yuliabaron I think this can closed.
