### ISSUE TITLE
Would be nice when the Maven plugin also provides a link to where the result of the scan can be found

### ISSUE THREAD

**Issue by marconew10** [snyk/snyk-maven-plugin#34]
The 'snyk:test' command in the end shows a link to the result of the scan at Snyk.io.

It would be nice when the Maven plugin shows the same during the mvn:test run.  At least, I'm assuming it _is_ producing a result at Snyk.io :)   

Best regards,
Marco

**Comment by JackuB** [comment]
@marconew10 the [Maven Plugin v2](https://github.com/snyk/snyk-maven-plugin/releases/tag/v2.0.0) now shows a `monitor` output, including the URL.
