### ISSUE TITLE
[enhancement] Ability to export results to a json file

### ISSUE THREAD

**Issue by madchap** [snyk/snyk-maven-plugin#44]
Hello,

It would be to be able to export results to a json file, to mimick for the CLI is doing. The json format should be strictly the same as the CLI's.

**Comment by JackuB** [comment]
@madchap the [Maven Plugin v2](https://github.com/snyk/snyk-maven-plugin/releases/tag/v2.0.0) now supports a JSON output because it's now based on CLI. It can be enabled by passing a `--json` flag:

```xml
<args>
  <arg>--json</arg>
</args>
```
